LIBNAME MOMO "\\R6-core\r6dfsvdi\JP1Share4\IBADW2N\Documents\‰Ò“­—¦";
Options compress=YES;
PROC SQL;
CREATE TABLE FOCUS_KEY
AS SELECT NIGIRI.F1 AS HIGHEST_PRODUCER_CD3, FMP.F1 AS HIGHEST_PRODUCER_CD2, NZK1.F1 AS HIGHEST_PRODUCER_CD,
NIGIRI.F2 AS NIGIRI_FLG, FMP.F2 AS FMP_FLG, NZK1.F2 AS NZK_FLG
FROM FMP FULL OUTER JOIN NZK1
ON FMP.F1=NZK1.F1
FULL OUTER JOIN NIGIRI
ON FMP.F1=NIGIRI.F1;
PROC SQL;
CREATE TABLE FOCUS_TABLE
AS SELECT
(CASE
WHEN HIGHEST_PRODUCER_CD2 IS NULL THEN HIGHEST_PRODUCER_CD
WHEN HIGHEST_PRODUCER_CD IS NULL THEN HIGHEST_PRODUCER_CD3
ELSE HIGHEST_PRODUCER_CD2 END) AS HIGHEST_PRODUCER_CD,
(CASE WHEN NZK_FLG IS NULL THEN '@' ELSE '@NZK' END) AS NZK_FLG,
(CASE WHEN FMP_FLG IS NULL THEN '@' ELSE '@FMP' END) AS FMP_FLG,
(CASE WHEN NIGIRI_FLG IS NULL THEN '@' ELSE '@NIGIRI' END) AS NIGIRI_FLG
FROM FOCUS_KEY;
PROC SQL;
CREATE TABLE FOCUS_FLG
AS SELECT
HIGHEST_PRODUCER_CD,
FMP_FLG,
NZK_FLG,
NIGIRI_FLG,
NZK_FLG||FMP_FLG||NIGIRI_FLG AS FLAG
FROM FOCUS_TABLE;
PROC SQL;
CREATE TABLE PRO_FOCUS
AS SELECT A.*,
B.FLAG
FROM MOMO.JEN_HON_PRO2 A LEFT JOIN FOCUS_FLG B
ON A.HIGHEST_PRODUCER_CD=B.HIGHEST_PRODUCER_CD;
/*PROC SQL;
CREATE TABLE FMP_NZK_NIGIRI_PRODUCER
AS SELECT * FROM PRO_FOCUS
WHERE FLAG IS NOT NULL;*/
PROC EXPORT
DATA=PRO_FOCUS
OUTFILE='\\R6-core\r6dfsvdi\JP1Share4\IBADW2N\Documents\Focus_Group\Focus_Test.csv'  DBMS=csv REPLACE;