LIBNAME MOMO "\\R6-core\r6dfsvdi\JP1Share4\IBADW2N\Documents\‰Ò“­—¦";
LIBNAME AIU ORACLE USER="" PASSWORD="" PATH='AIUPROD';
OPTIONS COMPRESS=YES;
PROC SQL;
CREATE TABLE FOCUS_JOIN
AS SELECT
A.*,
B.F2 AS NIGIRI_FLG,
C.F2 AS KAN_FMP_FLG,
D.F2 AS NZK_FLG,
E.F2 AS KPRO_FLG,
F.F2 AS FAA_FLG,
G.F2 AS ZEN_FMP_FLG
FROM AIU.JEN_HON_PRO2 A
LEFT JOIN NIGIRI 	B 	ON A.HIGHEST_PRODUCER_CD=B.F1
LEFT JOIN KAN_FMP 	C 	ON A.HIGHEST_PRODUCER_CD=C.F1
LEFT JOIN NZK 		D 	ON A.HIGHEST_PRODUCER_CD=D.F1
LEFT JOIN KPRO		E 	ON A.PRODUCER_CD		=E.F1
LEFT JOIN FAA 		F 	ON A.HIGHEST_PRODUCER_CD=F.F1
LEFT JOIN ZEN_FMP 	G 	ON A.HIGHEST_PRODUCER_CD=G.F1;
PROC SQL;
CREATE TABLE PRODUCER_INFO
AS SELECT
*,
NZK_FLG||'@'||KAN_FMP_FLG||'@'||NIGIRI_FLG||'@'||KPRO_FLG||'@'||FAA_FLG||'@'||ZEN_FMP_FLG AS AGENT_FLAG
FROM FOCUS_JOIN;
DATA PRO_INFO (DROP= NZK_FLG KAN_FMP_FLG NIGIRI_FLG KPRO_FLG FAA_FLG ZEN_FMP_FLG);
SET PRODUCER_INFO;
RUN; 
PROC EXPORT
DATA=PRO_INFO
OUTFILE='\\R6-core\r6dfsvdi\JP1Share4\IBADW2N\Documents\Focus_Group\PRO_INFO.csv' REPLACE DBMS=csv;