LIBNAME momo "\\RKDA0050\SME_team\Z_Working_files\Momoko\Focus Group";
LIBNAME jenn "\\rkda0050\SME_team\Z_Working_files\Jenny\SML Data_201804";
PROC SQL;
CREATE TABLE FOCUS_JOIN_ZEN
AS SELECT
A.*,
B.F2 AS FAA_FLG,
C.F2 AS ZEN_FMP_FLG
FROM AIU.JEN_HON_PRO2 A
LEFT JOIN FAA 		B 	ON A.HIGHEST_PRODUCER_CD=B.F1
LEFT JOIN ZEN_FMP 	C 	ON A.HIGHEST_PRODUCER_CD=C.F1;
PROC SQL;
CREATE TABLE FOCUS_JOIN_KAN
AS SELECT
A.HIGHEST_PRODUCER_CD,
A.PRODUCER_CD,
B.F2 AS NIGIRI_FLG,
C.F2 AS KAN_FMP_FLG,
D.F2 AS NZK_FLG,
E.F2 AS KPRO_FLG
FROM AIU.JEN_HON_PRO2 A
LEFT JOIN NIGIRI 	B 	ON A.HIGHEST_PRODUCER_CD=B.F1
LEFT JOIN KAN_FMP 	C 	ON A.HIGHEST_PRODUCER_CD=C.F1
LEFT JOIN NZK 		D 	ON A.HIGHEST_PRODUCER_CD=D.F1
LEFT JOIN KPRO		E 	ON A.PRODUCER_CD		=E.F1 /*Producer Cdにつき古い代理店があると複製されてしまう*/
WHERE 本部名2='05_関西地域事業本部';
PROC SQL;
CREATE TABLE FOCUS_KANSAI
AS SELECT DISTINCT *
FROM FOCUS_JOIN_KAN; /*Producer Cdにつきレコードが一つになるようにまとめる*/
PROC SQL;
CREATE TABLE FOCUS_JOIN
AS SELECT DISTINCT
B.*,
A.NIGIRI_FLG,
A.KAN_FMP_FLG,
A.NZK_FLG,
A.KPRO_FLG
FROM FOCUS_JOIN_ZEN B 
LEFT JOIN FOCUS_KANSAI A ON A.PRODUCER_CD=B.PRODUCER_CD; /*同じProducer Codeのレコードはすべて同じFlagがたつ*/
PROC SQL;
CREATE TABLE PRODUCER_INFO
AS SELECT DISTINCT
*,
NZK_FLG||'@'||KAN_FMP_FLG||'@'||NIGIRI_FLG||'@'||KPRO_FLG||'@'||FAA_FLG||'@'||ZEN_FMP_FLG AS AGENT_FLAG
FROM FOCUS_JOIN;
DATA PRO_INFO (DROP= NZK_FLG KAN_FMP_FLG NIGIRI_FLG KPRO_FLG FAA_FLG ZEN_FMP_FLG);
SET PRODUCER_INFO;
RUN;
DATA JENN.PRO_INFO;
SET PRO_INFO;
RUN;
DATA MOMO.PRO_INFO;
SET PRO_INFO;
RUN;
PROC SQL;
CREATE TABLE MOMO.CROSS_NEW
AS SELECT/* DISTINCT*/
A.COMPANY_FLG,
A.FY,
A.計上月,
A.ライン名,
A.商品群,
A.商品名,
A.SEGMENT,
A.BG有無,
B.本部名,
B.本部名2,
B.部支店名,
B.支店課名,
B.チャネル名,
B.チャネル大区分,
B.チャネル中区分,
B.チャネル小区分,
B.ソリシター名,
B.OPTIMIZE_TYP,
B.SUPPORT_MODEL,
B.FOCUS_FLG1,
B.FOCUS_FLG2,
B.FOCUS_FLG3,
B.ES区分,
B.ES名,
B.HIGHEST_PRODUCER_CD,
B.PRODUCER_CD,
B.OLD_PRODUCER_CD,
B.親代理店名,
B.代理店名,
B.AGENT_FLAG,
SUM(A.NOP) AS NOP,
SUM(A.ANP) AS ANP,
SUM(A.NOP_OLD) AS NOP_OLD,
SUM(A.ANP_OLD) AS ANP_OLD
FROM MOMO.CROSS_NEW_5 A
LEFT JOIN PRO_INFO B
ON A.PRODUCER_CD=B.OLD_PRODUCER_CD;
;
data JENN.focus_agent_cross; 
set momo.Cross_NEW;
run;
PROC EXPORT
DATA=Momo.CROSS_NEW
OUTFILE='\\RKDA0050\SME_team\Z_Working_files\Momoko\Focus Group\CROSS_NEW.csv' REPLACE DBMS=csv;